Mutation:
    type: object
    config:
        fields:
            NewCustomer:
                type: 'Customer'
                resolve: "@=mutation('NewCustomer', [args['input']])"
                args:
                    input:
                        description: 'The informations of the customer'
                        type: CustomerInput!

CustomerInput:
    type: input-object
    config:
        fields:
            firstName:
                type: "String"
            lastName:
                type: "String"
            city:
                type: "String"
            country:
                type: "String"
            socialSecurityNumber:
                type: "String"
            mobile:
                type: "String"
