Mutation:
    type: object
    config:
        fields:
            NewCustomer:
                type: 'Customer'
                resolve: "@=resolver('NewCustomer', [args['input']])"
                args:
                    input:
                        description: 'The informations of the customer'
                        type: String!
