Mutation:
    type: object
    config:
        fields:
            NewCustomer:
                type: 'Customer'
                resolve: "@=mutation('NewCustomer', [args['input']])"
                args:
                    input:
                        description: 'The informations of the customer'
                        type: CustomerInput!
            DeleteCustomer:
                type: 'Boolean'
                resolve: "@=mutation('DeleteCustomer', [args['id']])"
                args:
                    id:
                        description: 'Id of the user we want to remove'
                        type: Int!

CustomerInput:
    type: input-object
    config:
        fields:
            firstName:
                type: "String"
            lastName:
                type: "String"
            city:
                type: "String"
            country:
                type: "String"
            socialSecurityNumber:
                type: "String"
            mobile:
                type: "String"
