Mutation:
    type: object
    config:
        fields:
            NewCustomer:
                type: 'Customer'
                resolve: "@=mutation('NewCustomer', [args['input']])"
                args:
                    input:
                        description: 'The informations of the customer'
                        type: NewCustomerInput!
            EditCustomer:
                type: 'Customer'
                resolve: "@=mutation('EditCustomer', [args['id'], args['input']])"
                args:
                    id:
                        description: 'Id of the customer we want to remove'
                        type: Int!
                    input:
                        description: 'The informations of the customer'
                        type: EditCustomerInput!
            DeleteCustomer:
                type: 'Boolean'
                resolve: "@=mutation('DeleteCustomer', [args['id']])"
                args:
                    id:
                        description: 'Id of the user we want to remove'
                        type: Int!

NewCustomerInput:
    type: input-object
    config:
        fields:
            firstName:
                type: "String"
            lastName:
                type: "String"
            city:
                type: "String"
            country:
                type: "String"
            socialSecurityNumber:
                type: "String"
            mobile:
                type: "String"

EditCustomerInput:
    type: input-object
    config:
        fields:
            firstName:
                type: "String"
            lastName:
                type: "String"
            city:
                type: "String"
            country:
                type: "String"
            socialSecurityNumber:
                type: "String"
            mobile:
                type: "String"
            salary:
                type: "Int"